name: precipitation_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26
  - pillow
  - matplotlib
  - opencv
  - h5py
  - pandas
  - scikit-learn
  - seaborn
  - pip
  - pip:
    - xgboost>=2.0.0
    - openpyxl>=3.1.0
    - imbalanced-learn>=0.11.0 